apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xd5w1c009-go 
  janus-idp.io/tekton: xd5w1c009-go
  backstage.io/kubernetes-id: xd5w1c009-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xd5w1c009-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml